[build]
  command = "python -m mwb . output/"
  publish = "output/"

[[redirects]]
  from = "/conference_book.pdf"
  to = "https://static.midl.io/conference_book_2019.pdf"
  status = 302
  force = true
